// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9G7YmLrDfOp5rPJwu3LPkmAa_c0kO6-c',
    appId: '1:604306921005:web:b5c5b84e2285a1b7024aa4',
    messagingSenderId: '604306921005',
    projectId: 'kishor-first-app',
    authDomain: 'kishor-first-app.firebaseapp.com',
    databaseURL: 'https://kishor-first-app-default-rtdb.firebaseio.com',
    storageBucket: 'kishor-first-app.firebasestorage.app',
    measurementId: 'G-L6YP5WN0MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIdnsUJu3XaLSG2SQWEqDuh0NdUR7f6PE',
    appId: '1:604306921005:android:99d1a5c3061c155b024aa4',
    messagingSenderId: '604306921005',
    projectId: 'kishor-first-app',
    databaseURL: 'https://kishor-first-app-default-rtdb.firebaseio.com',
    storageBucket: 'kishor-first-app.firebasestorage.app',
  );
}
